---
title: "Publications"
format: html
editor: visual
bibliography: all_references.bib 
csl: apa.csl
link-citations: true
theme: minty 
---

[\<- Back to home page](http://clementinecttn.github.io/)

## Most recent {#publi-recent}

-   [@cottineau2025agent]: In this article, we model the social effect of urban segregation ‘around the clock’ on health behaviours (such as the choice of a healthy diet). We do so using an empirical agent-based model initialised on the Paris region with a synthetic population and a combination of scenarios of residential patterns (random allocation vs. census-based allocation reflecting the empirical level of residential segregation) with scenarios of daily mobility (no daily moves, random moves or survey-based daily moves reflecting the empirical level of daytime segregation in Paris). We find an increase in the uptake of healthy behaviours in all scenarios, but contrasted results with respect to social inequalities.

-   [@cottineau2025economic]: In this article, we review multilingual and multidisciplinary strands of literature on the causal pathways between economic inequality and economic segregation. We highlight the importance of temporality in the reverse causality between the two concepts. We also advocate for up-to-date comparable indices, new and diverse case studies, especially from unequal and segregated cities from non-dominant countries and a mutual awareness between empirical and theoretical research.

-   [@sanmillan2025wealth]: In this article, we explore how the spatiotemporal patterns of affluence and poverty differ when considering wealth versus income. By analyzing geo-coded microdata from the Netherlands, we show that wealth segregation is much higher than income segregation; that financial wealth is more unequally distributed than real estate wealth across society, but is more equally distributed across space; that wealth segregation is more sensitive to the spatial scale of measurement than income segregation; that income segregation is decreasing in most urban areas whereas wealth segregation is rising almost everywhere in the Netherlands.

-  [@san_millan_economic_2025]: In this article, we leverage geo-coded register data to computing income inequality and residential segregation measures annually in all urban areas of the Netherlands from 2011 to 2022. Contrary to most literature, this paper shows that inequality and segregation have remained stable or decreased in most cases. In addition, when looking at how income is distributed among social segments, how segregated they are, and at which geographical scale segregation occurs, we find significant variation between urban areas. More unequal urban areas also tend to be more segregated, but patterns vary, and the same segregation levels can coexist with diverse inequality metrics. Four groups of urban areas are identified through a cluster analysis.


## Scientific articles published within SEGUE {#publi-articles}

- on theories of urban inequality and segregation, literature reviews and the history of urban models:
 [@cottineau2024unforeseen] [@sarkar2024spatial] [@cottineau2024accommodating] [@SLRbanismWorkingPaper] [@cottineau2025agent] [@cottineau2025economic] 

- on empirical patterns of inequality and segregation  [@askenazy2024geography] [@san_millan_economic_2025] [@sanmillan2025wealth]  [@cottineau2025agent] 

-   on Agent-based modelling: [@achter2024conduct] [@cottineau2025agent] [@roxburg2025outlining]


## Books & chapters published within SEGUE {#publi-books}

-   Edited book on inequalities in geographical space: [@cottineau2022inequalities]

-   Edited book on cities and inequalities: [@cottineau2022cities]

- chapter in D. Rybski (dir.), 2025, *Compendium of Urban Complexity*:  [@cottineau2025citysize]

- chapter in C. Kosmopoulos & J. Schöpfel (dir.), 2025, *Publier, partager, réutiliser les données de la recherche: les data papers et leurs enjeux*: [@cottineau2025evaluer]

- chapter in R. Harris, A. Heppenstall, & L. J. Wolf (Eds.), 2024, *A research agenda for spatial analysis*: [@cottineau2024generative]


## Full list {#publi-list}

::: {#refs}
:::

[Back to home page](http://erc-segue.nl/)
